package color

import (
	"testing"

	"github.com/google/go-cmp/cmp"
)

func TestEnabledColors(t *testing.T) {
	cases := map[string]struct {
		red    bool
		green  bool
		blue   bool
		yellow bool
		want   []Color
	}{
		"red": {
			red:    true,
			green:  false,
			blue:   false,
			yellow: false,
			want: []Color{
				{Name: "Red", HexCode: "#ff0000"},
				{Name: "Maroon", HexCode: "#800000"},
				{Name: "Purple", HexCode: "#800080"},
				{Name: "Fuchsia", HexCode: "#ff00ff"},
			},
		},
		"green": {
			red:    false,
			green:  true,
			blue:   false,
			yellow: false,
			want: []Color{
				{Name: "Green", HexCode: "#008000"},
				{Name: "Aquamarine", HexCode: "#7fffd4"},
				{Name: "Charteuse", HexCode: "#7FFF00"},
				{Name: "DarkGreen", HexCode: "#006400"},
				{Name: "DarkOlvieGreen", HexCode: "#556B2F"},
				{Name: "DarkSeaGreen", HexCode: "#8FBC8F"},
				{Name: "ForestGreen", HexCode: "#228B22"},
				{Name: "GreenYellow", HexCode: "#ADFF2F"},
				{Name: "LawnGreen", HexCode: "#7CFC00"},
				{Name: "LightGreen", HexCode: "#80EE90"},
				{Name: "LightSeaGreen", HexCode: "#20B2AA"},
				{Name: "Lime", HexCode: "#00FF00"},
				{Name: "LimeGreen", HexCode: "#32CD32"},
				{Name: "MediumSeaGreen", HexCode: "#3CB371"},
				{Name: "MediumSpringGreen", HexCode: "#00FA9A"},
				{Name: "PaleGreen", HexCode: "#98FB98"},
				{Name: "SeaGreen", HexCode: "#2E8B57"},
				{Name: "SpringGreen", HexCode: "#00FF7F"},
				{Name: "Teal", HexCode: "#008080"},
				{Name: "YellowGreen", HexCode: "#9ACD32"},
			},
		},
		"blue": {
			red:    false,
			green:  false,
			blue:   true,
			yellow: false,
			want: []Color{
				{Name: "Blue", HexCode: "#0000ff"},
				{Name: "Aqua", HexCode: "#00ffff"},
				{Name: "Aliceblue", HexCode: "#f0f8ff"},
				{Name: "Azure", HexCode: "#f0ffff"},
				{Name: "BlueViolet", HexCode: "#8a2be2"},
				{Name: "CadetBlue", HexCode: "#5F9EA0"},
				{Name: "CornflowerBlue", HexCode: "#6495ED"},
				{Name: "Cyan", HexCode: "#00FFFF"},
				{Name: "DarkBlue", HexCode: "#00008B"},
				{Name: "DarkCyan", HexCode: "#008B8B"},
				{Name: "DarkSlateBlue", HexCode: "#483D8B"},
				{Name: "DarkSkyBlue", HexCode: "#00BFFF"},
				{Name: "DodgerBlue", HexCode: "#1E90FF"},
				{Name: "Indigo", HexCode: "#4B0082"},
				{Name: "Lavender", HexCode: "#E6E6FA"},
				{Name: "LightBlue", HexCode: "#ADD8E6"},
				{Name: "LightCyan", HexCode: "#E0FFFF"},
				{Name: "LightSkyBlue", HexCode: "#87CEFA"},
				{Name: "LightSteelBlue", HexCode: "#B0C4DE"},
				{Name: "MediumBlue", HexCode: "#0000CD"},
				{Name: "MediumSlateBlue", HexCode: "#7B68EE"},
				{Name: "MediumTurquoise", HexCode: "#48D1CC"},
				{Name: "MidnightBlue", HexCode: "#191970"},
				{Name: "Navy", HexCode: "#0000880"},
				{Name: "PaleTurquoise", HexCode: "#AFEEEE"},
				{Name: "PowderBlue", HexCode: "#B0E0E6"},
				{Name: "RoyalBlue", HexCode: "#4169E1"},
				{Name: "SkyBlue", HexCode: "#87CEEB"},
				{Name: "SlateBlue", HexCode: "#6A5ACD"},
				{Name: "SteelBlue", HexCode: "#4682B4"},
				{Name: "Turquoise", HexCode: "#40E0D0"},
			},
		},
		"yellow": {
			red:    false,
			green:  false,
			blue:   false,
			yellow: true,
			want: []Color{
				{Name: "Yellow", HexCode: "#ffff00"},
				{Name: "Olive", HexCode: "#808000"},
				{Name: "Orange", HexCode: "#ffa500"},
				{Name: "Beige", HexCode: "#f5f5dc"},
				{Name: "Bisque", HexCode: "#ffe4c4"},
				{Name: "BlanchedAlmond", HexCode: "#ffebcd"},
			},
		},
		"all": {
			red:    true,
			green:  true,
			blue:   true,
			yellow: true,
			want: []Color{
				{Name: "Red", HexCode: "#ff0000"},
				{Name: "Maroon", HexCode: "#800000"},
				{Name: "Purple", HexCode: "#800080"},
				{Name: "Fuchsia", HexCode: "#ff00ff"},
				{Name: "Green", HexCode: "#008000"},
				{Name: "Aquamarine", HexCode: "#7fffd4"},
				{Name: "Charteuse", HexCode: "#7FFF00"},
				{Name: "DarkGreen", HexCode: "#006400"},
				{Name: "DarkOlvieGreen", HexCode: "#556B2F"},
				{Name: "DarkSeaGreen", HexCode: "#8FBC8F"},
				{Name: "ForestGreen", HexCode: "#228B22"},
				{Name: "GreenYellow", HexCode: "#ADFF2F"},
				{Name: "LawnGreen", HexCode: "#7CFC00"},
				{Name: "LightGreen", HexCode: "#80EE90"},
				{Name: "LightSeaGreen", HexCode: "#20B2AA"},
				{Name: "Lime", HexCode: "#00FF00"},
				{Name: "LimeGreen", HexCode: "#32CD32"},
				{Name: "MediumSeaGreen", HexCode: "#3CB371"},
				{Name: "MediumSpringGreen", HexCode: "#00FA9A"},
				{Name: "PaleGreen", HexCode: "#98FB98"},
				{Name: "SeaGreen", HexCode: "#2E8B57"},
				{Name: "SpringGreen", HexCode: "#00FF7F"},
				{Name: "Teal", HexCode: "#008080"},
				{Name: "YellowGreen", HexCode: "#9ACD32"},
				{Name: "Blue", HexCode: "#0000ff"},
				{Name: "Aqua", HexCode: "#00ffff"},
				{Name: "Aliceblue", HexCode: "#f0f8ff"},
				{Name: "Azure", HexCode: "#f0ffff"},
				{Name: "BlueViolet", HexCode: "#8a2be2"},
				{Name: "CadetBlue", HexCode: "#5F9EA0"},
				{Name: "CornflowerBlue", HexCode: "#6495ED"},
				{Name: "Cyan", HexCode: "#00FFFF"},
				{Name: "DarkBlue", HexCode: "#00008B"},
				{Name: "DarkCyan", HexCode: "#008B8B"},
				{Name: "DarkSlateBlue", HexCode: "#483D8B"},
				{Name: "DarkSkyBlue", HexCode: "#00BFFF"},
				{Name: "DodgerBlue", HexCode: "#1E90FF"},
				{Name: "Indigo", HexCode: "#4B0082"},
				{Name: "Lavender", HexCode: "#E6E6FA"},
				{Name: "LightBlue", HexCode: "#ADD8E6"},
				{Name: "LightCyan", HexCode: "#E0FFFF"},
				{Name: "LightSkyBlue", HexCode: "#87CEFA"},
				{Name: "LightSteelBlue", HexCode: "#B0C4DE"},
				{Name: "MediumBlue", HexCode: "#0000CD"},
				{Name: "MediumSlateBlue", HexCode: "#7B68EE"},
				{Name: "MediumTurquoise", HexCode: "#48D1CC"},
				{Name: "MidnightBlue", HexCode: "#191970"},
				{Name: "Navy", HexCode: "#0000880"},
				{Name: "PaleTurquoise", HexCode: "#AFEEEE"},
				{Name: "PowderBlue", HexCode: "#B0E0E6"},
				{Name: "RoyalBlue", HexCode: "#4169E1"},
				{Name: "SkyBlue", HexCode: "#87CEEB"},
				{Name: "SlateBlue", HexCode: "#6A5ACD"},
				{Name: "SteelBlue", HexCode: "#4682B4"},
				{Name: "Turquoise", HexCode: "#40E0D0"},
				{Name: "Yellow", HexCode: "#ffff00"},
				{Name: "Olive", HexCode: "#808000"},
				{Name: "Orange", HexCode: "#ffa500"},
				{Name: "Beige", HexCode: "#f5f5dc"},
				{Name: "Bisque", HexCode: "#ffe4c4"},
				{Name: "BlanchedAlmond", HexCode: "#ffebcd"},
			},
		},
		"none": {
			red:    false,
			green:  false,
			blue:   false,
			yellow: false,
			want:   []Color{},
		},
	}

	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			res := EnabledColors(tc.red, tc.green, tc.blue, tc.yellow)
			if diff := cmp.Diff(tc.want, res); diff != "" {
				t.Errorf("unexpected result: (-want / +got)\n%s", diff)
			}
		})
	}
}
